#!/usr/bin/env python
import atexit
import os
import sys
from abc import ABCMeta, abstractmethod




class baseTerm(metaclass=ABCMeta):
	ANSI   = ...
	MODE   = ...
	BUFFER = ...

	def __init__(s,*a,**k):
		s.pid       = ...
		s.ppid      = ...
		s.input     = ...
		s.output    = ...
		s.error     =...

		# Components
		s.tty       = ...
		s.attr      = ...
		s.buffers	= ...
		s.colors    = ...
		s.cursor    = ...
		s.modes     = ...
		s.size      = ...
		s.atexit    = ...


		for attr in [a for a in dir(s) if not a.startswith('__')]:
			thisattr=getattr(s,attr)
			if hasattr(thisattr,'_postinit'):
				getattr(thisattr,'_postinit')()
		atexit.register(s.__cleanup__)


	def __cleanup__(s): ...

	@property
	@abstractmethod
	def buffer(s): ...

	@property
	@abstractmethod
	def mode(s): ...

	@buffer.setter
	@abstractmethod
	def buffer(s,buffer): ...

	@mode.setter
	@abstractmethod
	def mode(s, mode): ...