#!/usr/bin/env python
import atexit
import os
import sys
from abc import ABCMeta, abstractmethod




class baseTerm(metaclass=ABCMeta):
	ANSI   = ...
	MODE   = ...
	BUFFER = ...

	def __init__(s,*a,**k):
		s.pid       = ...
		s.ppid      = ...
		s.stdfd     = ...


		s.tty       = ...
		s._echo		= ...
		s._canon    = ...
		# Components
		s.attr      = ...
		s.stdin		= ...
		s.cursor    = ...
		s.size      = ...
		s.modes     = ...
		s.colors    = ...
		s.buffers	= ...
		s.atexit    = ...



	@abstractmethod
	def _update_(s, when):
		pass

	@property
	@abstractmethod
	def echo(s): ...

	@property
	@abstractmethod
	def buffer(s): ...

	@property
	@abstractmethod
	def canonical(s): ...

	@property
	@abstractmethod
	def mode(s): ...

	@buffer.setter
	@abstractmethod
	def buffer(s,buffer): ...

	@canonical.setter
	@abstractmethod
	def canonical(s, enable): ...

	@echo.setter
	@abstractmethod
	def echo(s, enable):  ...

	@mode.setter
	@abstractmethod
	def mode(s, mode): ...